/** @type {import('tailwindcss').Config} */
export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	theme: {
		extend: {
			colors: {
				'deep-teal': '#1A3835',
				'midnight-grey': '#292929',
				'misty-lavender': '#B1B5CA',
				'dark-indigo': '#272934',
				'frost-white': '#FCFDFC',
				'seafoam-green': '#E6F2ED',
				'ashen-grey': '#DFE3E1',
				'light-silver': '#D9D9D9',
				'steel-blue': '#242834',
				'charcoal-grey': '#57585F',
				'hunter-green': '#232F2D',
				evergreen: '#142E2B',
				'winter-mint': '#E9F3F2',
				'deep-forest': '#0C221F',
				'pale-jade': '#B3DFC9',
				'moss-green': '#43A57C',
				'blue-grey': '#788489',
				'sage-green': '#7BB99F',
				'opal-mist': '#EBF4F1',
				'spicy-apricot': '#FF9F5A',
			},
			fontFamily: {
				'inter-regular': ['Inter-Regular', 'sans-serif'],
				'inter-medium': ['Inter-Medium', 'sans-serif'],
				'inter-semi-bold': ['Inter-SemiBold', 'sans-serif'],
				'inter-bold': ['Inter-Bold', 'sans-serif'],
				'gilroy-regular': ['Gilroy-Regular', 'sans-serif'],
				'gilroy-medium': ['Gilroy-Medium', 'sans-serif'],
				'gilroy-semi-bold': ['Gilroy-SemiBold', 'sans-serif'],
				'gilroy-bold': ['Gilroy-Bold', 'sans-serif'],
			},
		},
	},
	plugins: [],
};
